# CMake generated Testfile for 
# Source directory: /home/lmz/gr-radar/python/radar
# Build directory: /home/lmz/gr-radar/build_fmcw0_clean/python/radar
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(qa_signal_generator_cw_c "/usr/bin/sh" "qa_signal_generator_cw_c_test.sh")
set_tests_properties(qa_signal_generator_cw_c PROPERTIES  _BACKTRACE_TRIPLES "/home/lmz/miniconda3/envs/gr310_fmcw_0/lib/cmake/gnuradio/GrTest.cmake;119;add_test;/home/lmz/gr-radar/python/radar/CMakeLists.txt;45;GR_ADD_TEST;/home/lmz/gr-radar/python/radar/CMakeLists.txt;0;")
add_test(qa_signal_generator_fmcw_c "/usr/bin/sh" "qa_signal_generator_fmcw_c_test.sh")
set_tests_properties(qa_signal_generator_fmcw_c PROPERTIES  _BACKTRACE_TRIPLES "/home/lmz/miniconda3/envs/gr310_fmcw_0/lib/cmake/gnuradio/GrTest.cmake;119;add_test;/home/lmz/gr-radar/python/radar/CMakeLists.txt;46;GR_ADD_TEST;/home/lmz/gr-radar/python/radar/CMakeLists.txt;0;")
add_test(qa_split_cc "/usr/bin/sh" "qa_split_cc_test.sh")
set_tests_properties(qa_split_cc PROPERTIES  _BACKTRACE_TRIPLES "/home/lmz/miniconda3/envs/gr310_fmcw_0/lib/cmake/gnuradio/GrTest.cmake;119;add_test;/home/lmz/gr-radar/python/radar/CMakeLists.txt;47;GR_ADD_TEST;/home/lmz/gr-radar/python/radar/CMakeLists.txt;0;")
add_test(qa_os_cfar_c "/usr/bin/sh" "qa_os_cfar_c_test.sh")
set_tests_properties(qa_os_cfar_c PROPERTIES  _BACKTRACE_TRIPLES "/home/lmz/miniconda3/envs/gr310_fmcw_0/lib/cmake/gnuradio/GrTest.cmake;119;add_test;/home/lmz/gr-radar/python/radar/CMakeLists.txt;48;GR_ADD_TEST;/home/lmz/gr-radar/python/radar/CMakeLists.txt;0;")
add_test(qa_ts_fft_cc "/usr/bin/sh" "qa_ts_fft_cc_test.sh")
set_tests_properties(qa_ts_fft_cc PROPERTIES  _BACKTRACE_TRIPLES "/home/lmz/miniconda3/envs/gr310_fmcw_0/lib/cmake/gnuradio/GrTest.cmake;119;add_test;/home/lmz/gr-radar/python/radar/CMakeLists.txt;49;GR_ADD_TEST;/home/lmz/gr-radar/python/radar/CMakeLists.txt;0;")
add_test(qa_estimator_cw "/usr/bin/sh" "qa_estimator_cw_test.sh")
set_tests_properties(qa_estimator_cw PROPERTIES  _BACKTRACE_TRIPLES "/home/lmz/miniconda3/envs/gr310_fmcw_0/lib/cmake/gnuradio/GrTest.cmake;119;add_test;/home/lmz/gr-radar/python/radar/CMakeLists.txt;50;GR_ADD_TEST;/home/lmz/gr-radar/python/radar/CMakeLists.txt;0;")
add_test(qa_static_target_simulator_cc "/usr/bin/sh" "qa_static_target_simulator_cc_test.sh")
set_tests_properties(qa_static_target_simulator_cc PROPERTIES  _BACKTRACE_TRIPLES "/home/lmz/miniconda3/envs/gr310_fmcw_0/lib/cmake/gnuradio/GrTest.cmake;119;add_test;/home/lmz/gr-radar/python/radar/CMakeLists.txt;51;GR_ADD_TEST;/home/lmz/gr-radar/python/radar/CMakeLists.txt;0;")
add_test(qa_signal_generator_fsk_c "/usr/bin/sh" "qa_signal_generator_fsk_c_test.sh")
set_tests_properties(qa_signal_generator_fsk_c PROPERTIES  _BACKTRACE_TRIPLES "/home/lmz/miniconda3/envs/gr310_fmcw_0/lib/cmake/gnuradio/GrTest.cmake;119;add_test;/home/lmz/gr-radar/python/radar/CMakeLists.txt;52;GR_ADD_TEST;/home/lmz/gr-radar/python/radar/CMakeLists.txt;0;")
add_test(qa_split_fsk_cc "/usr/bin/sh" "qa_split_fsk_cc_test.sh")
set_tests_properties(qa_split_fsk_cc PROPERTIES  _BACKTRACE_TRIPLES "/home/lmz/miniconda3/envs/gr310_fmcw_0/lib/cmake/gnuradio/GrTest.cmake;119;add_test;/home/lmz/gr-radar/python/radar/CMakeLists.txt;53;GR_ADD_TEST;/home/lmz/gr-radar/python/radar/CMakeLists.txt;0;")
add_test(qa_estimator_fsk "/usr/bin/sh" "qa_estimator_fsk_test.sh")
set_tests_properties(qa_estimator_fsk PROPERTIES  _BACKTRACE_TRIPLES "/home/lmz/miniconda3/envs/gr310_fmcw_0/lib/cmake/gnuradio/GrTest.cmake;119;add_test;/home/lmz/gr-radar/python/radar/CMakeLists.txt;54;GR_ADD_TEST;/home/lmz/gr-radar/python/radar/CMakeLists.txt;0;")
add_test(qa_usrp_echotimer_cc "/usr/bin/sh" "qa_usrp_echotimer_cc_test.sh")
set_tests_properties(qa_usrp_echotimer_cc PROPERTIES  _BACKTRACE_TRIPLES "/home/lmz/miniconda3/envs/gr310_fmcw_0/lib/cmake/gnuradio/GrTest.cmake;119;add_test;/home/lmz/gr-radar/python/radar/CMakeLists.txt;55;GR_ADD_TEST;/home/lmz/gr-radar/python/radar/CMakeLists.txt;0;")
add_test(qa_estimator_fmcw "/usr/bin/sh" "qa_estimator_fmcw_test.sh")
set_tests_properties(qa_estimator_fmcw PROPERTIES  _BACKTRACE_TRIPLES "/home/lmz/miniconda3/envs/gr310_fmcw_0/lib/cmake/gnuradio/GrTest.cmake;119;add_test;/home/lmz/gr-radar/python/radar/CMakeLists.txt;56;GR_ADD_TEST;/home/lmz/gr-radar/python/radar/CMakeLists.txt;0;")
add_test(qa_signal_generator_sync_pulse_c "/usr/bin/sh" "qa_signal_generator_sync_pulse_c_test.sh")
set_tests_properties(qa_signal_generator_sync_pulse_c PROPERTIES  _BACKTRACE_TRIPLES "/home/lmz/miniconda3/envs/gr310_fmcw_0/lib/cmake/gnuradio/GrTest.cmake;119;add_test;/home/lmz/gr-radar/python/radar/CMakeLists.txt;57;GR_ADD_TEST;/home/lmz/gr-radar/python/radar/CMakeLists.txt;0;")
add_test(qa_estimator_sync_pulse_c "/usr/bin/sh" "qa_estimator_sync_pulse_c_test.sh")
set_tests_properties(qa_estimator_sync_pulse_c PROPERTIES  _BACKTRACE_TRIPLES "/home/lmz/miniconda3/envs/gr310_fmcw_0/lib/cmake/gnuradio/GrTest.cmake;119;add_test;/home/lmz/gr-radar/python/radar/CMakeLists.txt;58;GR_ADD_TEST;/home/lmz/gr-radar/python/radar/CMakeLists.txt;0;")
add_test(qa_find_max_peak_c "/usr/bin/sh" "qa_find_max_peak_c_test.sh")
set_tests_properties(qa_find_max_peak_c PROPERTIES  _BACKTRACE_TRIPLES "/home/lmz/miniconda3/envs/gr310_fmcw_0/lib/cmake/gnuradio/GrTest.cmake;119;add_test;/home/lmz/gr-radar/python/radar/CMakeLists.txt;59;GR_ADD_TEST;/home/lmz/gr-radar/python/radar/CMakeLists.txt;0;")
add_test(qa_tracking_singletarget "/usr/bin/sh" "qa_tracking_singletarget_test.sh")
set_tests_properties(qa_tracking_singletarget PROPERTIES  _BACKTRACE_TRIPLES "/home/lmz/miniconda3/envs/gr310_fmcw_0/lib/cmake/gnuradio/GrTest.cmake;119;add_test;/home/lmz/gr-radar/python/radar/CMakeLists.txt;60;GR_ADD_TEST;/home/lmz/gr-radar/python/radar/CMakeLists.txt;0;")
add_test(qa_msg_gate "/usr/bin/sh" "qa_msg_gate_test.sh")
set_tests_properties(qa_msg_gate PROPERTIES  _BACKTRACE_TRIPLES "/home/lmz/miniconda3/envs/gr310_fmcw_0/lib/cmake/gnuradio/GrTest.cmake;119;add_test;/home/lmz/gr-radar/python/radar/CMakeLists.txt;61;GR_ADD_TEST;/home/lmz/gr-radar/python/radar/CMakeLists.txt;0;")
add_test(qa_msg_manipulator "/usr/bin/sh" "qa_msg_manipulator_test.sh")
set_tests_properties(qa_msg_manipulator PROPERTIES  _BACKTRACE_TRIPLES "/home/lmz/miniconda3/envs/gr310_fmcw_0/lib/cmake/gnuradio/GrTest.cmake;119;add_test;/home/lmz/gr-radar/python/radar/CMakeLists.txt;62;GR_ADD_TEST;/home/lmz/gr-radar/python/radar/CMakeLists.txt;0;")
add_test(qa_ofdm_cyclic_prefix_remover_cvc "/usr/bin/sh" "qa_ofdm_cyclic_prefix_remover_cvc_test.sh")
set_tests_properties(qa_ofdm_cyclic_prefix_remover_cvc PROPERTIES  _BACKTRACE_TRIPLES "/home/lmz/miniconda3/envs/gr310_fmcw_0/lib/cmake/gnuradio/GrTest.cmake;119;add_test;/home/lmz/gr-radar/python/radar/CMakeLists.txt;63;GR_ADD_TEST;/home/lmz/gr-radar/python/radar/CMakeLists.txt;0;")
add_test(qa_transpose_matrix_vcvc "/usr/bin/sh" "qa_transpose_matrix_vcvc_test.sh")
set_tests_properties(qa_transpose_matrix_vcvc PROPERTIES  _BACKTRACE_TRIPLES "/home/lmz/miniconda3/envs/gr310_fmcw_0/lib/cmake/gnuradio/GrTest.cmake;119;add_test;/home/lmz/gr-radar/python/radar/CMakeLists.txt;64;GR_ADD_TEST;/home/lmz/gr-radar/python/radar/CMakeLists.txt;0;")
add_test(qa_crop_matrix_vcvc "/usr/bin/sh" "qa_crop_matrix_vcvc_test.sh")
set_tests_properties(qa_crop_matrix_vcvc PROPERTIES  _BACKTRACE_TRIPLES "/home/lmz/miniconda3/envs/gr310_fmcw_0/lib/cmake/gnuradio/GrTest.cmake;119;add_test;/home/lmz/gr-radar/python/radar/CMakeLists.txt;65;GR_ADD_TEST;/home/lmz/gr-radar/python/radar/CMakeLists.txt;0;")
add_test(qa_ofdm_divide_vcvc "/usr/bin/sh" "qa_ofdm_divide_vcvc_test.sh")
set_tests_properties(qa_ofdm_divide_vcvc PROPERTIES  _BACKTRACE_TRIPLES "/home/lmz/miniconda3/envs/gr310_fmcw_0/lib/cmake/gnuradio/GrTest.cmake;119;add_test;/home/lmz/gr-radar/python/radar/CMakeLists.txt;66;GR_ADD_TEST;/home/lmz/gr-radar/python/radar/CMakeLists.txt;0;")
add_test(qa_os_cfar_2d_vc "/usr/bin/sh" "qa_os_cfar_2d_vc_test.sh")
set_tests_properties(qa_os_cfar_2d_vc PROPERTIES  _BACKTRACE_TRIPLES "/home/lmz/miniconda3/envs/gr310_fmcw_0/lib/cmake/gnuradio/GrTest.cmake;119;add_test;/home/lmz/gr-radar/python/radar/CMakeLists.txt;67;GR_ADD_TEST;/home/lmz/gr-radar/python/radar/CMakeLists.txt;0;")
add_test(qa_estimator_ofdm "/usr/bin/sh" "qa_estimator_ofdm_test.sh")
set_tests_properties(qa_estimator_ofdm PROPERTIES  _BACKTRACE_TRIPLES "/home/lmz/miniconda3/envs/gr310_fmcw_0/lib/cmake/gnuradio/GrTest.cmake;119;add_test;/home/lmz/gr-radar/python/radar/CMakeLists.txt;68;GR_ADD_TEST;/home/lmz/gr-radar/python/radar/CMakeLists.txt;0;")
add_test(qa_estimator_rcs "/usr/bin/sh" "qa_estimator_rcs_test.sh")
set_tests_properties(qa_estimator_rcs PROPERTIES  _BACKTRACE_TRIPLES "/home/lmz/miniconda3/envs/gr310_fmcw_0/lib/cmake/gnuradio/GrTest.cmake;119;add_test;/home/lmz/gr-radar/python/radar/CMakeLists.txt;69;GR_ADD_TEST;/home/lmz/gr-radar/python/radar/CMakeLists.txt;0;")
add_test(qa_trigger_command "/usr/bin/sh" "qa_trigger_command_test.sh")
set_tests_properties(qa_trigger_command PROPERTIES  _BACKTRACE_TRIPLES "/home/lmz/miniconda3/envs/gr310_fmcw_0/lib/cmake/gnuradio/GrTest.cmake;119;add_test;/home/lmz/gr-radar/python/radar/CMakeLists.txt;70;GR_ADD_TEST;/home/lmz/gr-radar/python/radar/CMakeLists.txt;0;")
subdirs("bindings")
